### ISSUE TITLE
max-len should be less for comments

### ISSUE THREAD

**Issue by borgar** [borgar/eslint-config#8]
https://eslint.org/docs/latest/rules/max-len

There are now options for comments specifically so we should update to more nuanced lengths:

Code: 120
Comments: 80

**Comment by gthb** [comment]
Done in https://github.com/borgar/eslint-config/commit/c840d8b829ce957ddbcc370a7498ee95c28314b3#diff-60ca788e9f9b374afa6f5a8a75211f1dab880bd183a1e39b87c44d2568138fe0 right?

**Comment by borgar** [comment]
Yes. Thank you! 🙂
